<?xml version="1.0" encoding="utf-8" ?>
<assemblies>
<assembly name="[assemblyLocation]" run-date="YYYY-MM-DD" run-time="HH:MM:SS" time="1.234" total="5" passed="1" failed="2" skipped="2" environment="00-bit .NET 1.2.3.4" test-framework="Fixie 1.2.3.4">
  <class time="1.234" name="[testClass]" total="5" passed="1" failed="2" skipped="2">
    <test name="[testClass].Fail" type="[testClass]" method="Fail" result="Fail" time="1.234">
      <failure exception-type="Fixie.Tests.FailureException">
        <message><![CDATA['Fail' failed!]]></message>
        <stack-trace><![CDATA[   at [testClassForStackTrace].Fail() in [fileLocation]:line #]]></stack-trace>
      </failure>
    </test>
    <test name="[testClass].FailByAssertion" type="[testClass]" method="FailByAssertion" result="Fail" time="1.234">
      <failure exception-type="Fixie.Assertions.AssertActualExpectedException">
        <message><![CDATA[Assertion Failure
Expected: 2
Actual:   1]]></message>
        <stack-trace><![CDATA[   at [testClassForStackTrace].FailByAssertion() in [fileLocation]:line #]]></stack-trace>
      </failure>
    </test>
    <test name="[testClass].Pass" type="[testClass]" method="Pass" result="Pass" time="1.234" />
    <test name="[testClass].SkipWithReason" type="[testClass]" method="SkipWithReason" result="Skip" time="1.234">
      <reason>
        <message><![CDATA[Skipped with reason.]]></message>
      </reason>
    </test>
    <test name="[testClass].SkipWithoutReason" type="[testClass]" method="SkipWithoutReason" result="Skip" time="1.234"/>
  </class>
</assembly>
</assemblies>